WARNING:root:Traceback (most recent call last):
  File "D:\flaskRaspberryApp\flask\monitor.py", line 32, in create_table
    cursor.execute(sql)
sqlite3.OperationalError: table Measure already exists

WARNING:root:Traceback (most recent call last):
  File "D:\flaskRaspberryApp\flask\monitor.py", line 32, in create_table
    cursor.execute(sql)
sqlite3.OperationalError: table Measure already exists

